# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fans',
            new_name='Fan',
        ),
    ]
