# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_auto_20180409_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_interest', models.CharField(default=None, max_length=20)),
                ('second_interest', models.CharField(default=None, max_length=20)),
                ('third_interest', models.CharField(default=None, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_system.User')),
            ],
        ),
    ]
