# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0004_auto_20180425_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=256),
        ),
    ]
