# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0007_remove_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
