# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0008_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='key_words',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default='老大叔', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='labels',
            field=models.CharField(default='待探索', max_length=100),
        ),
    ]
