# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0011_auto_20180502_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='title_link',
            field=models.URLField(default='www.baidu.com'),
        ),
    ]
