# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0012_history_title_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='item_title',
            field=models.CharField(default='news', max_length=50),
        ),
    ]
