# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0013_auto_20180502_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='first_interest',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='key_words',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='second_interest',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='third_interest',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
