# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0014_auto_20180504_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='labels',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
