# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0015_auto_20180505_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_link', models.URLField(default='www.baidu.com')),
                ('item_title', models.CharField(default='news', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='最喜欢', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.User')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.Label'),
        ),
    ]
