# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_title', models.CharField(default='news', max_length=50)),
                ('item_type', models.CharField(default='最新', max_length=5)),
                ('title_link', models.URLField()),
                ('cut_url', models.URLField()),
                ('collect_time', models.DateField(auto_now_add=True)),
                ('source', models.CharField(max_length=20)),
                ('like', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
            ],
        ),
    ]
