# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20180409_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='unknown author', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='unknown category', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='最新', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(default='unknown source', max_length=20),
        ),
    ]
