# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20180423_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='like',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='share',
            new_name='share_count',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='view',
            new_name='view_count',
        ),
    ]
