# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20180423_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=200, unique=True)),
                ('item_title', models.CharField(default='news', max_length=50)),
                ('item_type', models.CharField(default='最新', max_length=10)),
                ('title_link', models.URLField()),
                ('collect_time', models.DateField()),
                ('item_source', models.CharField(default='unknown source', max_length=20)),
                ('like_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
            ],
        ),
    ]
