# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_hititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hititem',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
