# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_hititem_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('item_title', models.CharField(default='图片', max_length=20)),
                ('collect_time', models.DateField()),
                ('item_source', models.CharField(default=20, max_length=10)),
                ('like_count', models.IntegerField(default=0)),
                ('category', models.CharField(default='你猜', max_length=10)),
            ],
        ),
    ]
